### ISSUE TITLE
New standard way of writing `docker-compose.yml`

### ISSUE THREAD

**Issue by tenshiAMD** [neckhair/rails-on-docker#7]
Based on https://docs.docker.com/compose/gettingstarted/. The new standard way of writing the `docker-compose.yml` is like this:

```
 version: '2'
 services:
    web:
         build: .
         ports:
          - "5000:5000"
         volumes:
          - .:/code
         depends_on:
          - redis
       redis:
         image: redis
```

I hope that this helps. 👍
